### ISSUE TITLE
请说下使用教程

### ISSUE THREAD

**Issue by chuangge123** [Lstaynight/xposed-dy#3]
看到该款软件，很感兴趣，但是不知道如何安装与使用？

**Comment by josh-zhu** [comment]
@sharmrock33 求加 qq359974136

**Comment by qqizai** [comment]
我也想请教下怎么个用法,  qq 1573372196

**Comment by yesiming** [comment]
@shamrock33 请教 qq 176089710

**Comment by samye465072111** [comment]
收到辣 谢谢

**Comment by samye465072111** [comment]
收到辣 谢谢

**Comment by xmhwws** [comment]
> 收到辣 谢谢

@samye465072111  能发一份给我吗？邮箱：[xmhwws@gmail.com](mailto:xmhwws@gmail.com)，感谢
